// Regenerates src/weapons/catalog.gen.ts from the JSON files in src/weapons/.
// Adding a weapon = drop a JSON file in src/weapons/ and run `pnpm --filter @sentinel/content gen`
// (the content tests fail with this hint if you forget). No hand-written code changes.
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export const weaponsDir = join(dirname(fileURLToPath(import.meta.url)), '../src/weapons');

export function renderCatalog(files) {
  const sorted = [...files].filter((f) => f.endsWith('.json')).sort();
  const ident = (f) => 'w_' + f.replace(/\.json$/, '').replace(/[^a-z0-9]/g, '_');
  return [
    '// GENERATED by packages/content/scripts/gen-catalog.mjs — do not edit.',
    ...sorted.map((f) => `import ${ident(f)} from './${f}' with { type: 'json' };`),
    '',
    '/** Every weapon JSON file, sorted by file name (the order gives stable wire indices). */',
    `export const weaponFiles: readonly unknown[] = [${sorted.map(ident).join(', ')}];`,
    `export const weaponFileNames: readonly string[] = ${JSON.stringify(sorted)};`,
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(join(weaponsDir, 'catalog.gen.ts'), renderCatalog(readdirSync(weaponsDir)));
  console.log('wrote src/weapons/catalog.gen.ts');
}
