// GENERATED by packages/content/scripts/gen-catalog.mjs — do not edit.
import w_halberd_mr from './halberd-mr.json' with { type: 'json' };
import w_kestrel_ar from './kestrel-ar.json' with { type: 'json' };
import w_thresher_12 from './thresher-12.json' with { type: 'json' };
import w_vireo_smg from './vireo-smg.json' with { type: 'json' };
import w_wren_sp from './wren-sp.json' with { type: 'json' };

/** Every weapon JSON file, sorted by file name (the order gives stable wire indices). */
export const weaponFiles: readonly unknown[] = [w_halberd_mr, w_kestrel_ar, w_thresher_12, w_vireo_smg, w_wren_sp];
export const weaponFileNames: readonly string[] = ["halberd-mr.json","kestrel-ar.json","thresher-12.json","vireo-smg.json","wren-sp.json"];
